# Generated by Django 5.2.4 on 2025-08-15 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0003_rename_is_passed_student_is_semester_student'),
        ('Courses', '0003_course_credit_hour'),
        ('Departments', '0004_alter_department_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks_Obtained', models.FloatField()),
                ('Total_Marks', models.FloatField(default=100)),
                ('Grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('Grade_Point', models.FloatField(default=0.0)),
                ('GPA', models.FloatField(default=0.0)),
                ('CGPA', models.FloatField(default=0.0)),
                ('Status', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Supply', 'Supply')], max_length=10)),
                ('Promote_Status', models.CharField(blank=True, choices=[('Promoted', 'Promoted'), ('Stay', 'Stay')], max_length=10)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.department')),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.coursecategories')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.student')),
            ],
            options={
                'unique_together': {('Student', 'Semester', 'Course')},
            },
        ),
    ]
