# Generated by Django 5.2.4 on 2025-08-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Grade_Point',
        ),
    ]
