# Generated by Django 5.2.4 on 2025-08-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_teacher_course_category'),
        ('Courses', '0007_remove_course_c_department'),
        ('Departments', '0004_alter_department_discription'),
        ('Grades', '0002_remove_grade_grade_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='Semester',
            new_name='Course_Category',
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('Student', 'Course_Category', 'Course')},
        ),
    ]
