# Generated by Django 5.2.4 on 2025-08-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_teacher_course_category'),
        ('Courses', '0007_remove_course_c_department'),
        ('Grades', '0003_rename_semester_grade_course_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('Student', 'Course')},
        ),
        migrations.AddField(
            model_name='grade',
            name='Attendance_Obtained_Marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='Attendance_Total_Marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='grade',
            name='Course_Obtained_Marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='Course_Total_Marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='grade',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='Sessional_Obtained_Marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='Sessional_Total_Marks',
            field=models.IntegerField(default=20),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='CGPA',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Course_Category',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='GPA',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Marks_Obtained',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Promote_Status',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Total_Marks',
        ),
    ]
