# Generated by Django 5.2.4 on 2025-08-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0004_alter_grade_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Attendance_Obtained_Marks',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Attendance_Total_Marks',
        ),
    ]
