# Generated by Django 5.2.4 on 2025-08-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0004_alter_department_discription'),
        ('Grades', '0005_remove_grade_attendance_obtained_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Departments.coursecategories'),
        ),
    ]
