# Generated by Django 5.2.4 on 2025-08-19 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_teacher_course_category'),
        ('Courses', '0007_remove_course_c_department'),
        ('Grades', '0006_grade_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=200)),
                ('credit_hour', models.FloatField(default=0)),
                ('course_total', models.FloatField(default=0)),
                ('course_obtained', models.FloatField(default=0)),
                ('sessional_total', models.FloatField(default=0)),
                ('sessional_obtained', models.FloatField(default=0)),
                ('total_obtained', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
