# Generated by Django 5.2.4 on 2025-08-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0007_studentgradehistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentgradehistory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentgradehistory',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentgradehistory',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.RemoveField(
            model_name='studentgradehistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentgradehistory',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='studentgradehistory',
            name='total_obtained',
        ),
    ]
