# Generated by Django 5.2.4 on 2025-08-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0008_alter_studentgradehistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgradehistory',
            name='GPA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentgradehistory',
            name='category_type',
            field=models.CharField(default='INTER', max_length=100),
        ),
        migrations.AddField(
            model_name='studentgradehistory',
            name='total_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentgradehistory',
            name='total_obtained',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentgradehistory',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
    ]
