# Generated by Django 5.2.4 on 2025-08-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0009_studentgradehistory_gpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgradehistory',
            name='pending_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentgradehistory',
            name='status',
            field=models.CharField(default='Pass', max_length=10),
        ),
    ]
