# Generated by Django 5.2.4 on 2025-08-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0010_studentgradehistory_pending_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='category',
        ),
    ]
