# Generated by Django 5.2.4 on 2025-08-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0012_grade_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='category',
        ),
    ]
