# Generated by Django 5.2.4 on 2025-08-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0002_rename_department_course_c_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz')], max_length=10)),
                ('Title', models.CharField(max_length=255)),
                ('Link', models.URLField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Ended_at', models.DateTimeField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
            ],
        ),
    ]
