# Generated by Django 5.2.4 on 2025-08-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments_and_Quizzes', '0001_initial'),
        ('Departments', '0004_alter_department_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='Category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Departments.coursecategories'),
        ),
    ]
