# Generated by Django 5.2.4 on 2025-08-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments_and_Quizzes', '0002_coursetask_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetask',
            name='Category_id',
        ),
    ]
