# Generated by Django 5.2.4 on 2025-08-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0013_student_supply_fee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Is_Read', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.student')),
                ('Teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.teacher')),
            ],
        ),
    ]
