# Generated by Django 5.2.4 on 2025-08-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_student_supply_fee_status'),
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Created_At',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Is_Read',
            new_name='for_all_students',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Title',
        ),
        migrations.AddField(
            model_name='notification',
            name='for_all_teachers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Account.student'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Account.teacher'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('hostel', 'Hostel'), ('fee', 'Fee'), ('library', 'Library'), ('event', 'Event'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
