# Generated by Django 5.2.4 on 2025-08-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Type', models.CharField(choices=[('INTER', 'Intermediate'), ('BS', 'Bachelor (Semester)'), ('3 SHORT', '3 Month Short Course'), ('4 SHORT', '6 Month Short Course'), ('5 SHORT', '12 Month Short Course')], max_length=10)),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=100)),
                ('Discription', models.TextField(blank=True, max_length=100)),
                ('Department_Image', models.ImageField(blank=True, null=True, upload_to='department_pics/')),
                ('HOD', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='Account.teacher')),
            ],
        ),
    ]
