# Generated by Django 5.2.4 on 2025-08-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategories',
            name='Related_Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Departments.department'),
        ),
        migrations.AlterField(
            model_name='coursecategories',
            name='Category_Name',
            field=models.CharField(choices=[('Part 1', 'Part 1'), ('Part 2', 'Part 2'), ('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8'), ('3 Months SC', '3 Month Short Course'), ('6 Months SC', '6 Month Short Course'), ('12 Months SC', '12 Month Short Course')], max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecategories',
            name='Category_Type',
            field=models.CharField(choices=[('INTER', 'Intermediate'), ('BS', 'Bachelor (Semester)'), ('Short Course', 'Short Course')], max_length=100),
        ),
    ]
