# Generated by Django 5.2.4 on 2025-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_coursecategories_related_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategories',
            name='Category_Name',
            field=models.CharField(choices=[('Part 1', 'Part 1'), ('Part 2', 'Part 2'), ('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8')], max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecategories',
            name='Category_Type',
            field=models.CharField(choices=[('INTER', 'Intermediate'), ('BS', 'Bachelor (Semester)')], max_length=100),
        ),
    ]
