# Generated by Django 5.2.4 on 2025-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0003_alter_coursecategories_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Discription',
            field=models.TextField(blank=True),
        ),
    ]
