# Generated by Django 5.2.4 on 2025-08-21 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_teacher_department_teacher_course'),
        ('Departments', '0004_alter_department_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='HOD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='Account.teacher'),
        ),
    ]
