# Generated by Django 5.2.4 on 2025-08-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_remove_teacher_course_teacher_department'),
        ('Departments', '0005_alter_department_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='HOD',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='Account.teacher'),
        ),
    ]
