# Generated by Django 5.2.4 on 2025-08-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0011_student_degree_status_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Challan_no', models.CharField(max_length=100, unique=True)),
                ('Challan_Type', models.CharField(max_length=100)),
                ('Amount_to_Pay', models.DecimalField(decimal_places=2, default=0, max_digits=100, unique=True)),
                ('Fine_Date', models.DateField(blank=True, null=True)),
                ('Fine_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=100, unique=True)),
                ('Amount_Paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('Amount_Date', models.DateField(blank=True, null=True)),
                ('Bank_Branch', models.CharField(max_length=100, unique=True)),
                ('Status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('Created_At', models.DateField(auto_now_add=True)),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.student')),
            ],
        ),
    ]
