# Generated by Django 5.2.4 on 2025-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeVoucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feevoucher',
            name='Challan_Type',
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='Fee_Type',
            field=models.CharField(choices=[('Department', 'Department'), ('Library', 'Library'), ('Hostel', 'Hostel'), ('Supply', 'Supply')], default='Department', max_length=50),
        ),
    ]
