# Generated by Django 5.2.4 on 2025-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeVoucher', '0002_remove_feevoucher_challan_type_feevoucher_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feevoucher',
            name='Fee_Type',
            field=models.CharField(choices=[('Intermediate', 'Intermediate'), ('Semester-wise', 'Semester-wise'), ('Library-fee', 'Library-fee'), ('Hostel-fee', 'Hostel-fee'), ('Supply-fee', 'Supply-fee')], default='Department', max_length=50),
        ),
    ]
