# Generated by Django 5.2.4 on 2025-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeVoucher', '0003_alter_feevoucher_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feevoucher',
            name='Fee_Type',
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='Challan_Type',
            field=models.CharField(choices=[('Intermediate', 'Intermediate'), ('Semester-wise', 'Semester-wise'), ('Library-fee', 'Library-fee'), ('Hostel-fee', 'Hostel-fee'), ('Supply-fee', 'Supply-fee')], default='Intermediate', max_length=50),
        ),
    ]
