# Generated by Django 5.2.4 on 2025-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeVoucher', '0004_remove_feevoucher_fee_type_feevoucher_challan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feevoucher',
            name='Challan_Type',
            field=models.CharField(choices=[('Admission-Processing', 'Admission-Processing'), ('Admission-fee', 'Admission-fee'), ('Intermediate', 'Intermediate'), ('Semester-wise', 'Semester-wise'), ('Library-fee', 'Library-fee'), ('Hostel-fee', 'Hostel-fee'), ('Supply-fee', 'Supply-fee')], default='Admission-Processing', max_length=50),
        ),
    ]
