# Generated by Django 5.2.4 on 2025-08-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeVoucher', '0005_alter_feevoucher_challan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feevoucher',
            name='Amount_Paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feevoucher',
            name='Amount_to_Pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feevoucher',
            name='Bank_Branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feevoucher',
            name='Fine_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
