# Generated by Django 5.2.4 on 2025-08-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeVoucher', '0006_alter_feevoucher_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feevoucher',
            name='Amount_Paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='feevoucher',
            name='Amount_to_Pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='feevoucher',
            name='Challan_Type',
            field=models.CharField(choices=[('Admission-Processing', 'Admission-Processing'), ('Admission-fee', 'Admission-fee'), ('Intermediate', 'Intermediate'), ('Semester-wise', 'Semester-wise'), ('Library-fee', 'Library-fee'), ('Hostel-fee', 'Hostel-fee'), ('Supply-fee', 'Supply-fee')], default='Admission-Processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='feevoucher',
            name='Fine_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
