# Generated by Django 5.2.4 on 2025-08-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0002_rename_department_course_c_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Video', models.FileField(upload_to='lectures_videos/')),
                ('Lec_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='Courses.course')),
            ],
        ),
    ]
