# Generated by Django 5.2.4 on 2025-08-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0002_initial'),
        ('Departments', '0004_alter_department_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Code', models.CharField(max_length=100)),
                ('C_Title', models.CharField(max_length=100)),
                ('C_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Departments.coursecategories')),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Departments.department')),
                ('Teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.teacher')),
            ],
        ),
    ]
