# Generated by Django 5.2.4 on 2025-08-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Department',
            new_name='C_Department',
        ),
    ]
