# Generated by Django 5.2.4 on 2025-08-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_rename_department_course_c_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Credit_Hour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
