# Generated by Django 5.2.4 on 2025-08-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_credit_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Credit_Hour',
            field=models.FloatField(default=0.0),
        ),
    ]
