# Generated by Django 5.2.4 on 2025-08-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_rename_is_passed_student_is_semester_student'),
        ('Courses', '0004_alter_course_credit_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Students',
            field=models.ManyToManyField(blank=True, to='Account.student'),
        ),
    ]
