# Generated by Django 5.2.4 on 2025-08-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Students',
        ),
    ]
