# Generated by Django 5.2.4 on 2025-08-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_remove_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='C_Department',
        ),
    ]
