# Generated by Django 5.2.4 on 2025-08-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_remove_course_c_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Teacher',
        ),
    ]
