# Generated by Django 5.2.4 on 2025-08-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_teacher_department_teacher_course'),
        ('Courses', '0008_remove_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.teacher'),
        ),
    ]
