# Generated by Django 5.2.4 on 2025-08-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='Department',
        ),
    ]
