# Generated by Django 5.2.4 on 2025-08-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0002_remove_timetable_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='Category',
        ),
    ]
