# Generated by Django 5.2.4 on 2025-09-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0003_remove_timetable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='End_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='Start_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
