# Generated by Django 5.2.4 on 2025-09-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0004_timetable_date_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_datesheet',
            field=models.BooleanField(default=False),
        ),
    ]
