# Generated by Django 5.2.4 on 2025-09-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0005_timetable_is_datesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='is_datesheet',
        ),
    ]
