# Generated by Django 5.2.4 on 2025-09-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0006_remove_timetable_is_datesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_datesheet',
            field=models.BooleanField(default=False),
        ),
    ]
