# Generated by Django 5.2.4 on 2025-08-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldetails',
            name='Hostel_Room_Image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_pics/'),
        ),
    ]
