# Generated by Django 5.2.4 on 2025-08-24 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_alter_hosteldetails_hostel_room_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosteldetails',
            options={'verbose_name': 'Hostel Detail', 'verbose_name_plural': 'Hostel Details'},
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=100)),
                ('ac', models.BooleanField(default=False)),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('wardrobe', models.BooleanField(default=False)),
                ('study_table', models.BooleanField(default=False)),
                ('common_area', models.BooleanField(default=False)),
                ('mess_facility', models.BooleanField(default=False)),
                ('laundry_facility', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Hostel.hosteldetails')),
            ],
        ),
    ]
