# Generated by Django 5.2.4 on 2025-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_alter_hosteldetails_options_roomdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_pics/'),
        ),
    ]
