# Generated by Django 5.2.4 on 2025-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0004_roomdetail_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='capacity',
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='available_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='booked_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='total_room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
