# Generated by Django 5.2.4 on 2025-08-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0005_remove_roomdetail_capacity_roomdetail_available_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='room_number',
        ),
    ]
