# Generated by Django 5.2.4 on 2025-08-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_remove_roomdetail_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Father_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Room_Type', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=100)),
                ('Home_Address', models.CharField(max_length=100)),
            ],
        ),
    ]
