# Generated by Django 5.2.4 on 2025-08-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0007_hostelapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelapplication',
            name='fee_generated_status',
            field=models.BooleanField(default=False),
        ),
    ]
