# Generated by Django 5.2.4 on 2025-08-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0008_hostelapplication_fee_generated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
