# Generated by Django 5.2.4 on 2025-08-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_student_supply_fee_status'),
        ('Hostel', '0009_hostelapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelapplication',
            name='Father_Name',
        ),
        migrations.RemoveField(
            model_name='hostelapplication',
            name='Student_Name',
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.student'),
        ),
    ]
