# Generated by Django 5.2.4 on 2025-08-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_student_supply_fee_status'),
        ('Hostel', '0010_remove_hostelapplication_father_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelCancelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Room_Type', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=100)),
                ('Home_Address', models.CharField(max_length=100)),
                ('Reason', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.student')),
            ],
        ),
    ]
