# Generated by Django 5.2.4 on 2025-08-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=100)),
                ('Reg_No', models.CharField(max_length=100, unique=True)),
                ('Roll_No', models.CharField(max_length=100, unique=True)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_CNIC', models.CharField(max_length=15, unique=True)),
                ('Student_Phone_No', models.CharField(blank=True, max_length=15, null=True)),
                ('Student_Email', models.EmailField(max_length=254, unique=True)),
                ('Student_Password', models.CharField(blank=True, max_length=128, null=True)),
                ('Student_Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('Student_DOB', models.DateField(blank=True, null=True)),
                ('Student_Father_Name', models.CharField(max_length=100)),
                ('Father_CNIC_No', models.CharField(max_length=15, unique=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Matric_Roll_No', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Matric_Obtained_Marks', models.PositiveIntegerField(blank=True, null=True)),
                ('Matric_Total_Marks', models.PositiveIntegerField(blank=True, null=True)),
                ('Matric_Board', models.CharField(blank=True, max_length=100, null=True)),
                ('Matric_Year', models.PositiveIntegerField(blank=True, null=True)),
                ('Matric_Session', models.CharField(blank=True, max_length=100, null=True)),
                ('Intermediate_Roll_No', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Intermediate_Obtained_Marks', models.PositiveIntegerField(blank=True, null=True)),
                ('Intermediate_Total_Marks', models.PositiveIntegerField(blank=True, null=True)),
                ('Intermediate_Board', models.CharField(blank=True, max_length=100, null=True)),
                ('Intermediate_Year', models.PositiveIntegerField(blank=True, null=True)),
                ('Intermediate_Session', models.CharField(blank=True, max_length=100, null=True)),
                ('Is_Registered', models.BooleanField(default=False)),
                ('Is_Passed', models.BooleanField(default=False)),
                ('OTP_Digits', models.CharField(blank=True, max_length=6, null=True)),
                ('OTP_Expiry', models.DateTimeField(blank=True, null=True)),
                ('Is_Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=100)),
                ('Teacher_Name', models.CharField(max_length=100)),
                ('Teacher_Email', models.EmailField(max_length=254, unique=True)),
                ('Teacher_Password', models.CharField(blank=True, max_length=128, null=True)),
                ('Teacher_OTP_Digits', models.CharField(blank=True, max_length=6, null=True)),
                ('Teacher_OTP_Expiry', models.DateTimeField(blank=True, null=True)),
                ('Teacher_Is_Verified', models.BooleanField(default=False)),
            ],
        ),
    ]
