# Generated by Django 5.2.4 on 2025-07-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsit_semester_1_students',
            name='Student_DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
