# Generated by Django 5.2.4 on 2025-08-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Departments.coursecategories'),
        ),
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Departments.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='Departments.department'),
        ),
    ]
