# Generated by Django 5.2.4 on 2025-08-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Is_Passed',
            new_name='Is_Semester_Student',
        ),
    ]
