# Generated by Django 5.2.4 on 2025-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_bsit_semester_1_students_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(choices=[('BSIT', 'BS Information Technology'), ('BSZoo', 'BS Zoology'), ('BSEcon', 'BS Economics'), ('BSEng', 'BS English'), ('BSUrd', 'BS Urdu'), ('BSMaths', 'BS Mathematics'), ('BSPS', 'BS Political Science'), ('BSstat', 'BS Statistics')], max_length=100)),
                ('Semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=100)),
                ('Reg_No', models.CharField(max_length=100, unique=True)),
                ('University_Roll_No', models.CharField(max_length=100, unique=True)),
                ('Roll_No', models.CharField(max_length=100, unique=True)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_CNIC', models.CharField(max_length=15, unique=True)),
                ('Student_Phone_No', models.CharField(max_length=15)),
                ('Student_Email', models.EmailField(max_length=254, unique=True)),
                ('Student_Gender', models.CharField(max_length=10)),
                ('Student_DOB', models.DateField()),
                ('Student_Father_Name', models.CharField(max_length=100)),
                ('Father_CNIC_No', models.CharField(max_length=15, unique=True)),
                ('Father_Contact_Number', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Matric_Roll_No', models.CharField(max_length=100, unique=True)),
                ('Matric_Board', models.CharField(max_length=100)),
                ('Matric_Year', models.PositiveIntegerField()),
                ('Matric_Session', models.CharField(max_length=100)),
                ('Intermediate_Roll_No', models.CharField(max_length=100, unique=True)),
                ('Obtained_Marks', models.PositiveIntegerField()),
                ('Total_Marks', models.PositiveIntegerField()),
                ('Intermediate_Board', models.CharField(max_length=100)),
                ('Intermediate_Year', models.PositiveIntegerField()),
                ('Intermediate_Session', models.CharField(max_length=100)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BSIT_Semester_1_Students',
        ),
    ]
