# Generated by Django 5.2.4 on 2025-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_student_delete_bsit_semester_1_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Obtained_Marks',
            new_name='Intermediate_Obtained_Marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Total_Marks',
            new_name='Intermediate_Total_Marks',
        ),
        migrations.AddField(
            model_name='student',
            name='Matric_Obtained_Marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Matric_Total_Marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
