# Generated by Django 5.2.4 on 2025-08-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_rename_is_passed_student_is_semester_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='can_access_Course',
            field=models.BooleanField(default=False),
        ),
    ]
