# Generated by Django 5.2.4 on 2025-08-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_student_can_access_course'),
        ('Departments', '0004_alter_department_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Course_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='Departments.coursecategories'),
        ),
    ]
