# Generated by Django 5.2.4 on 2025-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_rename_obtained_marks_student_intermediate_obtained_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
