# Generated by Django 5.2.4 on 2025-08-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_teacher_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Course_Category',
        ),
    ]
