# Generated by Django 5.2.4 on 2025-08-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_student_father_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='University_Roll_No',
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Gender',
            field=models.CharField(choices=[('1', 'Male'), ('1', 'Female')], max_length=10),
        ),
    ]
