# Generated by Django 5.2.4 on 2025-08-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_teacher_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Department',
        ),
    ]
