# Generated by Django 5.2.4 on 2025-08-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_remove_student_department'),
        ('Courses', '0008_remove_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Department',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='Courses.course'),
        ),
    ]
