# Generated by Django 5.2.4 on 2025-08-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_remove_student_university_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
