# Generated by Django 5.2.4 on 2025-08-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_teacher_department_teacher_course'),
        ('Departments', '0005_alter_department_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Course',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='Departments.department'),
        ),
    ]
