# Generated by Django 5.2.4 on 2025-08-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_student_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_passed',
            new_name='Is_Passed',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='is_registered',
            new_name='Is_Registered',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_password',
            new_name='Student_Password',
        ),
    ]
