# Generated by Django 5.2.4 on 2025-08-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_remove_teacher_course_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Supply', 'Supply')], default='Pass', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='Supply_Courses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
