# Generated by Django 5.2.4 on 2025-08-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_rename_is_passed_student_is_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Is_Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='OTP_Digits',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='OTP_Expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
