# Generated by Django 5.2.4 on 2025-08-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_student_status_student_supply_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Degree_Status',
            field=models.CharField(choices=[('Running', 'Running'), ('Complete', 'Complete')], default='Running', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Status',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Supply', 'Supply')], max_length=10, null=True),
        ),
    ]
