# Generated by Django 5.2.4 on 2025-08-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_student_is_verified_student_otp_digits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Role',
            field=models.CharField(default='Student', editable=False, max_length=20),
        ),
    ]
