# Generated by Django 5.2.4 on 2025-08-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_student_degree_status_alter_student_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Is_Semester_Student',
            new_name='Fee_Status',
        ),
    ]
