# Generated by Django 5.2.4 on 2025-08-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_student_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=100),
        ),
    ]
