# Generated by Django 5.2.4 on 2025-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=100)),
                ('Teacher_Name', models.CharField(max_length=100)),
                ('Teacher_Email', models.EmailField(max_length=254, unique=True)),
                ('Teacher_Password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
