# Generated by Django 5.2.4 on 2025-08-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_rename_is_semester_student_student_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Supply_Fee_Status',
            field=models.BooleanField(default=False),
        ),
    ]
