# Generated by Django 5.2.4 on 2025-08-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Is_Verified',
            field=models.BooleanField(default=False),
        ),
    ]
