# Generated by Django 5.2.4 on 2025-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_student_supply_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Teacher_Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
