# Generated by Django 5.2.4 on 2025-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_teacher_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='OTP_Digits',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='OTP_Expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
