# Generated by Django 5.2.4 on 2025-08-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_student_student_image_teacher_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
