# Generated by Django 5.2.4 on 2025-08-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_teacher_otp_digits_teacher_otp_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Is_Verified',
            new_name='Teacher_Is_Verified',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='OTP_Digits',
            new_name='Teacher_OTP_Digits',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='OTP_Expiry',
            new_name='Teacher_OTP_Expiry',
        ),
    ]
