# Generated by Django 5.2.4 on 2025-09-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_teacher_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Temp_Password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Temp_Password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
