# Generated by Django 5.2.4 on 2025-09-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_student_temp_password_teacher_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Supply_Fee_Status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='can_access_Course',
        ),
    ]
