# Generated by Django 5.2.4 on 2025-08-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Email', models.EmailField(max_length=254, unique=True)),
                ('Admin_Password', models.CharField(blank=True, max_length=256, null=True)),
                ('Is_Verified', models.BooleanField(default=False)),
                ('OTP_Digits', models.CharField(blank=True, max_length=6, null=True)),
                ('OTP_Expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
