# Generated by Django 5.2.4 on 2025-09-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Temp_Password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
