# Generated by Django 5.2.4 on 2025-08-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_alter_feedback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
